### ISSUE TITLE
Undefined and null are not objects

### ISSUE THREAD

**Issue by jacobwgillespie** [twolfson/google-music.js#12]
I'm seeing the following errors with google-music.js - they appear to be happening each time a song changes:

<img width="829" alt="screenshot 2015-12-04 13 33 04" src="https://cloud.githubusercontent.com/assets/130874/11599298/aa060fba-9a8b-11e5-8de5-034f75b6583f.png">

Line numbers are messed up as the file gets minifed by the WebView injection, so line 209 is https://github.com/twolfson/google-music.js/blob/cb2e3f29243913d4240381fcb982471cff74c398/dist/google-music.js#L240 and 277 is https://github.com/twolfson/google-music.js/blob/cb2e3f29243913d4240381fcb982471cff74c398/dist/google-music.js#L240

**Comment by twolfson** [comment]
About to get back from vacation and deal with a large backlog. I will take a look by the end of next weekend. I think I have seen something similar before but `google-music-electron` was still working.

Note to self: It might be a good idea to add Sentry, Errorception, or any of the other browser-side error trackers for errors that occur in `google-music.js` for `google-music-electron`.

**Comment by twolfson** [comment]
Alright, took a stab at this and resolved the issues. The test suite needed a little TLC as well so that was addressed as well. Everything has been published in `google-music.js@3.3.0`.

A gist of the changes:
- Repaired tests for `play-pause-status` (queue clearing and I'm Feeling Lucky were broken)
- Repaired `rating.getRating` integration (broke after `paper` updates)
- Repaired `classList.contains` error (started receiving text nodes in mutation updates)
- Repaired `el.$.icon...` error (started checking non-rating buttons on rating updates)

**Comment by jacobwgillespie** [comment]
Nice, thanks!  :+1:
