### ISSUE TITLE
Advanced playback controls

### ISSUE THREAD

**Issue by MarshallOfSound** [twolfson/google-music.js#36]
I am looking into adding methods such as `getCurrentQueue()`, `getPlaylists()`, `playPlaylist(name)` and events like `change:queue` and `change:playlistlist`.

Obviously the naming of these methods needs to be thought through a bit more but my main question here is do we feel that these methods could belong on `gmusic.js` or should they be in a separate repository?

/cc @gmusic-utils/gmusic-js

**Comment by twolfson** [comment]
I think they belong in this repo and I agree that the names/events need some work =P

**Comment by MarshallOfSound** [comment]
| Proposed Method Namespace | Proposed Method Name | Desired Action |
| --- | --- | --- |
| playlist | `list()` | List all playlists the user has |
| playlist | `play(name)` | Play a playlist with a given name |
| playlist | `add()` | Triggers the new playlist dialog |
| playlist | `open(name)` | Opens the playlist with a given name, but does not start playing |
| queue | `clear()` | Resets the current queue to be empty |
| queue | `list()` | Returns an array of song objects that make up the current queue |

Still thinking of better names for the events.  But what do you think of these methods @twolfson

**Comment by twolfson** [comment]
Was writing comment but @MarshallOfSound so here's what I was writing while I write something else:

---

Feedback on the proposed methods/names:
- `getCurrentQueue()`
  - Rename to `getQueue()` as there's only 1 active queue
  - Return value would be an array of song objects?
- `change:queue`
  - Is this when any song is added/removed or queue order changes?
  - Would there be any data in this event?
- `change:playlistlist` - I think we meant `change:playlist` but I'm not sure what this event would be for...
- `getPlaylists()` - Good name/method
  - Would we return objects (e.g. `{id, name}`) or solely names/ids?
- `playPlaylist(name)`

Additional feedback in the same category:
- Do we list "Auto-playlists" in `getPlaylists()`

**Comment by twolfson** [comment]
Interesting thoughts about putting them in their own namespace. I figured we could place them in `playback` since they are related to that. I will have to think about that some more.

**Comment by twolfson** [comment]
So I can better understand the feature, can you explain why you want this integration?

**Comment by MarshallOfSound** [comment]
@twolfson Basically I have implemented a WebSocket API inside my desktop player (docs [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md#controlling-the-application)) and as part of that you can recieve updates on the "state" of the player and control the player through all the methods availible in this library.

Someone (woo hoo) has started using this API to make a remote for the player.  (I think this is awesome :+1: ) 

https://github.com/mmazzarolo/google-play-music-desktop-remote

But they are looking for more control over what is playing, what is in the queue and triggering certain things playing.  I think this is a fair enough request and figured the best place to implement these additional controller methods was here.

**Comment by twolfson** [comment]
Ah, neat. I usually ask to minimize YAGNI (any code we write is code we have to maintain).

As a security heads up, the default `ws` listener seems to be on `0.0.0.0` which means it accepts connections from any server, not only the local computer. It seems that this is always being enabled without user opt-in which is probably a bad idea (I don't want an attacker to shut off my Google Music remotely let alone do something more malicious by exploiting Electron).

Relevant code:
- https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/e59aab9e3b3a517f8e31d13f6c5f7c84d1c1652a/src/main/features/core/websocketAPI.js#L110-L119
- https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/e59aab9e3b3a517f8e31d13f6c5f7c84d1c1652a/src/main/features/core/websocketAPI.js#L45-L50
- https://github.com/websockets/ws/blob/1242a8ca0de7668fc5fe1ddbfba09d42e95aa7cc/lib/WebSocketServer.js#L22-L31

I can think of 2 solutions:
- Add a CLI flag/user setting to opt in to automatically starting the WebSocket server
- Add a `host: 127.0.0.1` to only allow local IPv4 connections to the `ws` constructor

Also, please use `wss://` not `ws://` since that's the secure version of WebSockets (so nobody can sniff packets).

**Comment by twolfson** [comment]
I'm heads down on something else at the moment but will jump back to naming/methods later. I didn't want to lose that security thought though.

**Comment by MarshallOfSound** [comment]
The websocket is off by default and only turned on with user interaction in the settings window.  The line `Settings.get("playbackAPI", false)`  fetches the setting that indicates if the API should be enabled and the "false" indicates it's default is false

**Comment by MarshallOfSound** [comment]
wss is an interesting point, users connecting will have to ignore certificate errors

**Comment by twolfson** [comment]
Ah, my eyes missed `Settings.get` -- for some reason I thought the emitter was `gmusic.js` detecting someone hitting play =X

With respect to `wss`, it's prob better to have than not. Otherwise, you will have packet sniffing and man in the middle attacks to worry about. Charles Proxy and Burp work around this by offering SSL certificates that are distinct to each machine they are installed on:
- Charles Proxy offers integrated support on Windows/OS X. For other platforms, it offers downloading the certificate via its UI as well as setting up a proxy at `http://www.charlesproxy.com/getssl`  which serves the certificate
  - https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/
- Burp handles sets up a local HTTP server which serves the certificate
  - https://portswigger.net/burp/help/proxy_options_installingCAcert.html

**Comment by twolfson** [comment]
Anyway, back to the topic at hand... playlists/queues.

**Comment by twolfson** [comment]
The suggested naming isn't too consistent with our existing scheme (e.g. `getX`, `setX`, `toggleX`). How about the following:
- `playlists.getAll()` - Returns array of playlist objects
  - For example, `[{id: 'abcdef', name: 'Top 40'}]`
- `playlists.getPlaylist(id)` - Returns specific playlist object by its id
  - We prob don't need to implement this but it's here for CRUDL consistency
  - For example, `{id: 'abcdef', name: 'Top 40'}`
- `playlists.playPlaylist(id)` - Play a playlist based on its id
  - We want `id` since there could be multiple playlists with the same name
- `playlists.openAddDialog()` - Opens the add playlist dialog
  - I'm avoiding `add()` since that implies it can do everything, not only open a dialog
  - Also, are we sure someone wants support for this? It seems silly for a remote UI if they can't fully save
- ~~`playslists.open(name)`~~ - I don't see anything in Google Music that directly supports this behavior
  - If users want to roll their own complex actions, we should let them but let's keep this library low level
- `playlists.addPlaylistToQueue(id)` - Adds playlist to existing queue
  - Accessed via `...` dialog in playlists in sidebar
    - ![selection_224](https://cloud.githubusercontent.com/assets/902488/14308008/d34acbcc-fb98-11e5-8e7a-df3a43d2bbf7.png)
  - Probably what we meant by `open`

For handling queue, I think `playback` is the appropriate namespace since `getCurrentSong()` feels like it should live there and `getSongs()` is its respective "list" action
- `playback.clearQueue()` - Stops playback and empties queue
- `playback.getCurrentSong()` - Returns current song object
  - Use same object structure as `change:song`
- `playback.getSongs()` - Returns array of song objects

I'm not sure where `change:queue` fits in but I never got clarification on what its purpose was =/

**Comment by MarshallOfSound** [comment]
I agree with all those names, I did feel like I wasn't quite matching but I didn't put much effort into nailing it :laughing: 

As for the two events here is what I imagined them doing

The playlist related change event would be fired whenever a new playlist was added, a playlist was renamed or a playlist was deleted.  Hence the original name `change:playlistList` I.e. Whenever the list of playlists changes

The queue related one would fire whenever the queue changed.  I.e. A song was added or removed or just the entire queue changed for some reason.

**Comment by MarshallOfSound** [comment]
Oh and in regards to `playlists.open(name | id)` I meant that this method would simulate the user clicking on the playlist in the sidebar and effectively navigate to that playlist in the UI.

**Comment by twolfson** [comment]
Ah, k. I'm realizing that we don't namespace our events so we should be fine. Feedback on those events:
- `change:playlists` - This is prob more consistent name than `playlistList`
  - Did we want to emit with the new list of playlists or not include any data?
- `change:queue` - The name is good but same question about data (i.e. do we include anything or not)

**Comment by MarshallOfSound** [comment]
Plan was to send out the new list of playlists with the playlist event.  Same with the queue.  It seems consistent with our current events (sending out the new data in the event)

**Comment by twolfson** [comment]
For naming, I would recommend `playlists.navigateTo(id)` as a replacement for `playlists.open`? Or maybe even we define a `ui` namespace and make `ui.navigateToPlaylist(id)`, `ui.navigateToArtists`, etc

But, I don't follow when it would be reasonable for remote UI control if there's no actions being taken. Can you find out what the plans are?

**Comment by MarshallOfSound** [comment]
I have lots of these methods working locally but I am having trouble forcing a navigation to the playlist I want to play.  It appears as though any navigation that isn't caused by GPM itself or any "trusted" user interaction causes a whole load of internal GPM errors... :cry:

**Comment by MarshallOfSound** [comment]
I've tried everything from simulating clicks on the menu, to `history.pushState` to `window.location = ''` and even `window.location.hash = ''` but everything throws stupid errors

**Comment by twolfson** [comment]
You never answered my question about why we want to support that behavior =/

Similarly, "why support `openAddDialog()`" hasn't been answered as well =/

**Comment by MarshallOfSound** [comment]
Just heading to sleep but basically in order to play a playlist you need to be on that playlists page so navigating to it is kind of a must.

As for `openAddDialog` I don't think that that is strictly required :+1:

**Comment by twolfson** [comment]
Hmm, now that I'm thinking more about it. Adding support for playlists seems a bit convoluted as we don't support playing albums directly at the moment (which for some users are their "playlists", e.g. myself).

Maybe we should break it down into further actions?
- `playlists.navigateTo(id)`
- `playlists.playCurrentPlaylist()`

Or maybe we should finally get around to controlling the Angular app directly instead of its UI =/

**Comment by twolfson** [comment]
Fwiw, setting `window.location` seems to work in my console in `google-music-electron`:

```
// Get URL of Listen Now
> window.location.href
"https://play.google.com/music/listen#/now"
// Select a playlist and get its URL
> window.location.href
"https://play.google.com/music/listen#/pl/AMaBXynXCz5mJ7BuRQF3bVIdYyOKEd7jMayjZZH9ug3BnEO9Ih8rEPBr92PiI1KBwwERPpOipHPFxLN0K26hiIJqT_y4Xu4hHA%3D%3D"
// Navigate back to Listen Now
// Set location and watch page change
> window.location = "https://play.google.com/music/listen#/pl/AMaBXynXCz5mJ7BuRQF3bVIdYyOKEd7jMayjZZH9ug3BnEO9Ih8rEPBr92PiI1KBwwERPpOipHPFxLN0K26hiIJqT_y4Xu4hHA%3D%3D"
```

**Comment by twolfson** [comment]
Another option might be seeing how Chromecast integrates as well as Google Music's mini player Chrome extension. Those might give us insight into lower level APIs.

**Comment by twolfson** [comment]
Stared at the Google Music source code again. I downloaded the Music Player form the Chrome App Store. After digging around, it seems to use `chrome.runtime.sendMessage` to send messages so I looked at `getEventListeners(window).message` in Google Music. I found some things like `gadgets.rpc` which seem promising but I can't find out if they are a red herring or not.

If you want to dig around the Chrome extension source, it can be downloaded via the following:

https://gist.github.com/twolfson/b78c5d37a4a6a8fe8c07e784c3c26e51

**Comment by MarshallOfSound** [comment]
@twolfson `window.location` does work from console.  But for some reason if you call it from within the GMusic library it then throws a whole load of errors and it ceases to work in console...

This is messing with my head

**Comment by twolfson** [comment]
Can you link to the code you are using and the errors you are receiving?

**Comment by MarshallOfSound** [comment]
Pushed to a branch up here

https://github.com/gmusic-utils/gmusic.js/blob/feature/playlists/lib/main.js#L286

**Comment by MarshallOfSound** [comment]
Just run `(new GMusic(window)).playlists.getAll()[0].play()` and watch errors flood your console

**Comment by twolfson** [comment]
I'm not in a good spot to set up `gmusic.js` at the moment, can you copy/paste the error?

**Comment by twolfson** [comment]
Fwiw, the URL resolution can be simplified by leveraging the `url` library:

``` js
var urlObj = url.parse(window.location.href);
urlObj.pathname = '/music/listen/pl/' + encodeURIComponent(id);
window.locaiton = url.stringify(urlObj);
```

Also, `escape` doesn't properly handle all URL characters (e.g. it skips `@`). It's suggested to use `encodeURIComponent` instead:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by MarshallOfSound** [comment]
![log2capture](https://cloud.githubusercontent.com/assets/6634592/14340197/926487a2-fcc8-11e5-9a51-d0c1cc144004.PNG)
![logcapture](https://cloud.githubusercontent.com/assets/6634592/14340198/926555d8-fcc8-11e5-8953-3e4b1bbf7d78.PNG)

**Comment by MarshallOfSound** [comment]
Worth pointing out that none of those errors have a stack trace that comes back to our code.  It appears to be event listeners or something.  I have no idea how the code even triggers

**Comment by twolfson** [comment]
Weird. As a sanity check, can you use something without the regexp or `url` library like we did in the console?

For example:

``` js
// Be sure to change URL to a playlist in your account
window.location = 'https://play.google.com/music/listen#/pl/AMaBXynXCz5mJ7BuRQF3bVIdYyOKEd7jMayjZZH9ug3BnEO9Ih8rEPBr92PiI1KBwwERPpOipHPFxLN0K26hiIJqT_y4Xu4hHA%3D%3D';
```

**Comment by MarshallOfSound** [comment]
Yep, I've tried hardcoding the URL to switch to, and it still throws those errors.  But not when you run the exact same code in console

**Comment by twolfson** [comment]
Heh, well I guess that rules out that strategy. My suggestions for researching other venues:
- Look at `getEventListeners(window)`; there might be a history listener or hashchange listener that shines a light on the issue
- Dig around the source code
  - Various tools/resources that help http://twolfson.com/2015-07-31-slacks-source-code-is-beautiful#further-reading-tools

**Comment by twolfson** [comment]
I should mention that it sounds like the end user is essentially rebuilding Google Music's UI with us as an API. However, there are other projects that already rebuild Google Music by using their undocumented API. The end user will likely have better results with that:
- https://github.com/simon-weber/gmusicapi
- http://gmusicproxy.net/
- https://github.com/malept/gmusicprocurator

**Comment by mmazzarolo** [comment]
May I join the discussion?  :)  
I don't know if you were talking about my project or just targeting a generic end user, but I started the WebSocket API discussion mainly for re-starting the playlist when it ends (and of course implementing endpoints like `.on('change:shuffle')` that were already available in gmusic).  
Obviously I would be happy to implement other features in the remote player if you add new endpoints (and if I still have free time, I can't take it for granted unfortunately :cold_sweat:) in the future but maybe it would be better to first check how many other people are interested in the APIs.  
Anyway thank you guys, I learned a lot just by reading this thread :+1:

**Comment by twolfson** [comment]
I missed the issue cross-reference earlier but here it is again:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/845

Another option to consider: Since you are building a remote UI, you can build a UI sync rather than rebuild a programmatic interface (e.g. on the phone you navigate to the same HTTP pages; see http://www.html5rocks.com/en/tutorials/tooling/synchronized-cross-device-testing/).

The caveat here would be Google Music doesn't handle responsive CSS at the moment. For reference, we have set up custom CSS via `gmusic-theme.js`. Overall though, responsive CSS would be more than these controls for a locally hosted server (e.g. someone could set up userstyles with responsive CSS) and we wouldn't have to go through the trouble of reverse engineering everything in Google Music without touching its UI (I don't even want to think about search x_x).

**Comment by MarshallOfSound** [comment]
Closing because `gmusic-ui.js`
